version: '3'
services: 
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
#    environment:
#      - NODE_ENV=development
#    command: npm start
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    env_file:
      - ./.ENV_DB
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:



